#!/usr/bin/env bash
# Run the ten-cluster behavioural calibration on one allocated Seagull node.
# Submit from the login node; all extraction-independent computation below runs
# only after Slurm has allocated the job:
#
# Canonical five-session thesis invocation (required):
#
#   sbatch --export=ALL,MULTIDAY_POOLING_PROVENANCE=/shared/pool/pooling_provenance.json,POOLING_PRODUCER_PROJECT_ROOT=/shared/pool-producer-source \
#     submit_cluster_value_agent_calibration.sh
#
# The provenance file is made by submit_five_day_pooled_training.sh.  It fixes
# the five 2019 training sessions, their individual empirical target roots,
# the pooled training direct inputs, and the 2020-01-30 development-validation
# opening and target source.  That date is not claimed as an independent final
# holdout after this protocol revision.  This script refuses a provenance file
# whose dates do not match the declared five-session protocol.  A legacy
# one-session configuration is intentionally rejected because it cannot carry
# the certified five-day pooled spread/depth feedback targets.
#
# The job deliberately needs one MPI rank at a time: this is compact
# behavioural-policy fitting, not the distributed scaling experiment.  The
# The resulting policy is consumed by the queue-reactive validation and final
# liquidity-shock launchers.
#
# Change literal #SBATCH directives, or override them at submission time.
#SBATCH --job-name=lob-cluster-cal
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
# The full protocol adds 25 full-day, full-universe training-adequacy paths
# after candidate selection. This three-day allocation is a fail-safe ceiling,
# not an expected runtime; it remains below Seagull's four-day job limit.
#SBATCH --time=3-00:00:00
#SBATCH --output=slurm/%x-%j.out
#SBATCH --error=slurm/%x-%j.err

set -Eeuo pipefail

: "${SLURM_JOB_ID:?submit this file with sbatch}"
: "${SLURM_SUBMIT_DIR:?SLURM_SUBMIT_DIR is unavailable}"

# This must be the schema-v7 pooling_provenance.json emitted by the current
# five-day pooling job.  Fail at shell startup rather than beginning a cluster
# allocation with an unsupported one-session protocol.
: "${MULTIDAY_POOLING_PROVENANCE:?provide schema-v7 five-day pooling_provenance.json}"
# A reused pool is bound to the exact source tree that produced its recorded
# workflow hash. This must be explicit: silently treating the current tree as
# the producer of an older pool would weaken provenance. Any model or workflow
# semantic change requires a pool generated by this exact source tree.
: "${POOLING_PRODUCER_PROJECT_ROOT:?provide the source-tree root that produced MULTIDAY_POOLING_PROVENANCE}"
MULTIDAY_EXPECTED_TRAINING_DATES="2019-01-30,2019-03-27,2019-07-30,2019-10-30,2019-12-30"
MULTIDAY_EXPECTED_HELDOUT_DATE="2020-01-30"

# The workflow uses three block-coordinate searches: global background/local
# controls, compact per-cluster value policies, then a global shared-MM quote
# proxy.  The disabled value-policy baseline is included explicitly by the
# Python driver as a comparator, not as an additional hand-tuned model.
CLUSTERS="10"
VALIDATION_PER_CLUSTER="3"
MINIMUM_CLUSTER_SIZE="6"
CLUSTER_SEED="20200130"
STAGE1_DURATION="300"
STAGE2_DURATION="3600"
SESSION_DURATION="23400"
STAGE1_TOP_CANDIDATES="6"
STAGE1_REFINEMENT_CANDIDATES="32"
STAGE2_TOP_CANDIDATES="2"
STAGE1_SEEDS="1729"
STAGE2_SEEDS="1729,7919"
STAGE3_SEEDS="1729,7919,1103,6599,2027"
# Training winners reached the former 15-bps grid boundary.  The 25- and
# 40-bps candidates are therefore a preregistered training-grid expansion, not
# a response to the 2020 development-validation outcome.
THRESHOLDS="5,8,10,15,25,40"
DEPTH_PARTICIPATIONS="0.05,0.1,0.25,0.5"
# Hawkes rate files were analytically inverted at 0.30; this is a direct-input
# convention, not a post-hoc behavioural search dimension.
HAWKES_ACTIVITY_SCALES="0.30"
LOCAL_MM_INTERVALS_MS="500,1000,2000"
LOCAL_MM_QUANTITY_MULTIPLIERS="0.5,1.0,2.0"
LOCAL_MM_IMPROVEMENT_PROBABILITIES="0,0.25,0.5,1"
SHARED_QUOTE_MULTIPLIERS="0.5,1.0,2.0"
SHARED_TREATMENT_MULTIPLIER="1.0"
# A full-day, full-universe held-out run on one rank can legitimately exceed
# 15 minutes.  This is a per-simulator-run guard, not the Slurm job limit.
TIMEOUT_SECONDS="${TIMEOUT_SECONDS:-21600}"

PROJECT_DIR="${SLURM_SUBMIT_DIR}"
BUILD_DIR="${BUILD_DIR:-${PROJECT_DIR}/build-seagull-gcc15-ompi509-cluster-cal-${SLURM_JOB_ID}}"
RESULT_DIR="${RESULT_DIR:-${PROJECT_DIR}/results/seagull/cluster_value_calibration_${SLURM_JOB_ID}}"
BUILD_JOBS="${BUILD_JOBS:-${SLURM_CPUS_PER_TASK:-1}}"
# This suffix is Seagull's Spack build identifier, not a model revision.
SEAGULL_GCC_MODULE="gcc/15.2.0-gcc-8.5.0-r7c4jsu"
SEAGULL_MODULES="${SEAGULL_MODULES:-${SEAGULL_GCC_MODULE} openmpi/5.0.9-gcc-15.2.0-2irqibq cmake/3.31.9-gcc-15.2.0-ylutpfi ninja/1.13.0-gcc-15.2.0-nukwcsd python/3.14.2-gcc-15.2.0-e63sscp}"

fail() {
    echo "ERROR: $*" >&2
    exit 2
}

positive_integer() {
    local name="$1" value="$2"
    [[ "${value}" =~ ^[0-9]+$ ]] && (( value > 0 )) \
        || fail "${name} must be a positive integer; observed '${value}'."
}

absolute_file() {
    python3 - "$1" <<'PY'
import pathlib
import sys
path = pathlib.Path(sys.argv[1]).expanduser().resolve()
if not path.is_file():
    raise SystemExit(f"ERROR: not a regular file: {path}")
print(path)
PY
}

absolute_directory() {
    python3 - "$1" <<'PY'
import pathlib
import sys
path = pathlib.Path(sys.argv[1]).expanduser().resolve()
if not path.is_dir():
    raise SystemExit(f"ERROR: not a directory: {path}")
print(path)
PY
}

load_multiday_pooling_provenance() {
    # Emit a compact, tab-delimited manifest only after every referenced input
    # has been resolved and validated. Newlines and tabs are rejected in paths
    # so Bash can consume this transport format without shell eval.
    local manifest="$1"
    local expected_training="$2"
    local expected_heldout="$3"
    local rows
    rows="$(python3 - "${manifest}" "${expected_training}" "${expected_heldout}" <<'PY'
import csv
import hashlib
import json
import math
import pathlib
import sys
from datetime import date

manifest_path = pathlib.Path(sys.argv[1]).expanduser().resolve()
expected_training = [item for item in sys.argv[2].split(",") if item]
expected_heldout = sys.argv[3]

def fail(message: str) -> None:
    raise SystemExit(f"ERROR: invalid MULTIDAY_POOLING_PROVENANCE: {message}")

if not manifest_path.is_file():
    fail(f"not a regular file: {manifest_path}")
try:
    payload = json.loads(manifest_path.read_text(encoding="utf-8"))
except (OSError, json.JSONDecodeError) as error:
    fail(f"cannot read JSON {manifest_path}: {error}")
if not isinstance(payload, dict):
    fail("top-level JSON value is not an object")
if payload.get("schema_version") != 7:
    fail(
        "unsupported pooling schema; rerun five-day pooling with the current "
        "balanced stationary-rate runtime configuration workflow"
    )
if payload.get("method") != "multi_day_direct_input_pooling_with_day_level_behavioural_wmm":
    fail("does not identify the supported multi-day direct-input pooling method")

base_fields = [
    "book_id", "symbol", "data_dir", "hawkes_rates_file",
    "fundamental_price_ticks", "initial_best_bid_ticks",
    "initial_best_ask_ticks", "initial_best_bid_depth",
    "initial_best_ask_depth", "beta", "basket_weight",
    "market_maker_quote_quantity", "target_spread_ticks",
    "quote_improvement_probability",
]
runtime_fields = [
    *base_fields, "fundamental_volatility_bps_sqrt_second",
    "fundamental_move_probability_per_second",
    "fundamental_conditional_kurtosis",
    "target_mean_bid_depth", "target_mean_ask_depth",
]
pooled_homeostatic_fields = [
    "target_spread_ticks", "target_mean_bid_depth", "target_mean_ask_depth",
]
latent_value_fields = [
    "fundamental_volatility_bps_sqrt_second",
    "fundamental_move_probability_per_second",
    "fundamental_conditional_kurtosis",
]
frozen_training_derived_fields = [
    *pooled_homeostatic_fields, *latent_value_fields,
]
schema_digest = hashlib.sha256(json.dumps(
    runtime_fields, ensure_ascii=True, separators=(",", ":")
).encode("utf-8")).hexdigest()
expected_schema = {
    "schema_version": 5,
    "source_fields": base_fields,
    "runtime_fields": runtime_fields,
    "runtime_fields_sha256": schema_digest,
    "pooled_homeostatic_fields": pooled_homeostatic_fields,
    "latent_value_fields": latent_value_fields,
    "frozen_training_derived_fields": frozen_training_derived_fields,
    "queue_reactive_target_fields": [
        "target_mean_bid_depth", "target_mean_ask_depth",
    ],
    "positive_queue_reactive_targets_required": True,
    "same_pooled_targets_in_all_runtime_sessions": True,
    "heldout_target_files_used": False,
}
if payload.get("configuration_schema") != expected_schema:
    fail("pool has an unsupported or unhashed runtime configuration schema")

expected_improvement_approximation = {
    "schema_version": 2,
    "status": "preflight_passed",
    "descriptive_empirical_rate": (
        "inside_spread_limit_orders / improvement_eligible_limit_orders; "
        "eligible means pre-add displayed spread >= two simulator ticks"
    ),
    "runtime_estimand": (
        "inside_spread_limit_orders / "
        "(limit_buy_distance_zero_count + limit_sell_distance_zero_count)"
    ),
    "runtime_mapping": (
        "apply one aggregate maximum-symmetry split after a buy or sell "
        "distance-zero mark is sampled and only when the simulated spread "
        "is at least two ticks"
    ),
    "exact_joint_mark_calibration": False,
    "side_and_state_joint_counts_identified": False,
    "reduced_form_maximum_symmetry_zero_split": True,
    "probability_clamping_permitted": False,
    "compatibility_criterion": (
        "inside_spread_limit_orders <= "
        "limit_buy_distance_zero_count + limit_sell_distance_zero_count"
    ),
    "absolute_tolerance": 1.0e-12,
    "scope": (
        "every training-day and pooled symbol configuration; held-out "
        "runtime backgrounds are frozen from pooled training inputs"
    ),
}
if payload.get("quote_improvement_runtime_approximation") != (
        expected_improvement_approximation):
    fail(
        "pool lacks the fail-closed quote-improvement compatibility preflight"
    )

# Refuse legacy pools that include sub-dollar/sub-penny opening regimes.  The
# current C++ simulator has one fixed 100-unit (USD 0.01) tick, so accepting an
# older provenance artifact would reproduce the PHUN validation failure only
# after the expensive three-block calibration had completed.
eligibility = payload.get("opening_price_grid_eligibility")
if not isinstance(eligibility, dict):
    fail(
        "missing opening_price_grid_eligibility; rerun "
        "submit_five_day_pooled_training.sh with the current code"
    )
if eligibility.get("simulator_tick_size_price_units") != 100:
    fail("pool was not screened for the simulator's fixed 100-unit price tick")
minimum_opening_bid = eligibility.get("minimum_opening_bid_price_units")
if not isinstance(minimum_opening_bid, int) or minimum_opening_bid < 10_000:
    fail("pool opening-bid floor is below the supported USD 1.00 price regime")
intersection_count = eligibility.get("intersection_symbol_count")
eligible_count = eligibility.get("eligible_symbol_count")
excluded_count = eligibility.get("excluded_symbol_count")
excluded_symbols = eligibility.get("excluded_symbols")
if not all(isinstance(value, int) and value >= 0 for value in (
        intersection_count, eligible_count, excluded_count)):
    fail("opening price-grid eligibility counts are invalid")
if eligible_count + excluded_count != intersection_count:
    fail("opening price-grid eligibility counts do not reconcile")
if not isinstance(excluded_symbols, list) or len(excluded_symbols) != excluded_count:
    fail("opening price-grid exclusion records do not reconcile")
if payload.get("common_symbol_count") != eligible_count:
    fail("common_symbol_count does not match the screened eligible count")
if eligible_count != 1480:
    fail(
        "certified calibration requires exactly 1480 common symbols after "
        f"the fixed-tick eligibility screen; observed {eligible_count}"
    )
pooling = payload.get("pooling")
hawkes = pooling.get("hawkes") if isinstance(pooling, dict) else None
if not isinstance(hawkes, dict):
    fail("pooling provenance lacks Hawkes inversion settings")
if pooling.get("heldout_targets_used_for_runtime_configuration") is not False:
    fail("pool does not prove that held-out targets were excluded from runtime inputs")
expected_hawkes = {
    "activity_scale": 0.30,
    "kernel_beta": 10.0,
    "balance_directional_volume": True,
    "balance_best_depth": True,
    "balance_strength": 1.0,
    "excitation_structure": "diagonal_self_excitation_only",
    "self_excitation_amplitude": 0.20,
    "cross_excitation_amplitude": 0.0,
}
for key, expected in expected_hawkes.items():
    if hawkes.get(key) != expected:
        fail(
            f"pooling Hawkes setting {key}={hawkes.get(key)!r}; "
            f"canonical profile requires {expected!r}"
        )

def valid_date(value: object, label: str) -> str:
    if not isinstance(value, str):
        fail(f"{label} is not a string")
    try:
        date.fromisoformat(value)
    except ValueError:
        fail(f"{label} is not ISO YYYY-MM-DD: {value!r}")
    return value

def valid_path(value: object, label: str, *, directory: bool = False) -> str:
    if not isinstance(value, str) or not value:
        fail(f"{label} is missing")
    if "\n" in value or "\r" in value or "\t" in value:
        fail(f"{label} contains an unsupported control character")
    path = pathlib.Path(value).expanduser().resolve()
    if directory:
        if not path.is_dir():
            fail(f"{label} is not a directory: {path}")
    elif not path.is_file():
        fail(f"{label} is not a regular file: {path}")
    return str(path)

def verify_sha256(path_value: str, recorded: object, label: str) -> None:
    if not isinstance(recorded, str) or len(recorded) != 64 \
            or any(character not in "0123456789abcdefABCDEF" for character in recorded):
        fail(f"{label} has no valid recorded SHA-256")
    digest = hashlib.sha256()
    with pathlib.Path(path_value).open("rb") as source:
        for block in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(block)
    observed = digest.hexdigest()
    if observed.lower() != recorded.lower():
        fail(
            f"{label} SHA-256 mismatch: manifest={recorded.lower()} "
            f"observed={observed} path={path_value}"
        )

def runtime_targets(path_value: str, label: str) -> dict[str, tuple[str, ...]]:
    path = pathlib.Path(path_value)
    try:
        with path.open(newline="", encoding="utf-8") as source:
            reader = csv.DictReader(source)
            fields = list(reader.fieldnames or [])
            rows = list(reader)
    except OSError as error:
        fail(f"cannot read {label}: {error}")
    if fields != runtime_fields or not rows:
        fail(f"{label} does not use runtime schema version 5")
    result: dict[str, tuple[str, ...]] = {}
    for line_number, row in enumerate(rows, start=2):
        symbol = str(row.get("symbol", "")).strip().upper()
        if not symbol or symbol in result:
            fail(f"{label} has an invalid symbol at line {line_number}")
        values: list[str] = []
        for field in frozen_training_derived_fields:
            rendered = str(row.get(field, "")).strip()
            try:
                number = float(rendered)
            except ValueError:
                fail(f"{label}:{line_number}:{field} is not numeric")
            if not math.isfinite(number):
                fail(f"{label}:{line_number}:{field} must be finite")
            if (field in latent_value_fields
                    and field != "fundamental_conditional_kurtosis"
                    and number < 0.0):
                fail(f"{label}:{line_number}:{field} must be non-negative")
            if (field == "fundamental_move_probability_per_second"
                    and number > 1.0):
                fail(f"{label}:{line_number}:{field} must not exceed one")
            if (field == "fundamental_conditional_kurtosis"
                    and number < 1.0):
                fail(f"{label}:{line_number}:{field} must be at least one")
            if field not in latent_value_fields and number <= 0.0:
                fail(f"{label}:{line_number}:{field} must be positive")
            values.append(rendered)
        result[symbol] = tuple(values)
    return result

def runtime_rate_paths(path_value: str, label: str) -> dict[str, str]:
    path = pathlib.Path(path_value)
    try:
        with path.open(newline="", encoding="utf-8") as source:
            reader = csv.DictReader(source)
            fields = list(reader.fieldnames or [])
            rows = list(reader)
    except OSError as error:
        fail(f"cannot read {label}: {error}")
    if fields != runtime_fields or not rows:
        fail(f"{label} does not use runtime schema version 5")
    result: dict[str, str] = {}
    for line_number, row in enumerate(rows, start=2):
        symbol = str(row.get("symbol", "")).strip().upper()
        if not symbol or symbol in result:
            fail(f"{label} has an invalid symbol at line {line_number}")
        result[symbol] = valid_path(
            row.get("hawkes_rates_file"),
            f"{label}:{line_number}:hawkes_rates_file",
        )
    return result

def verify_rate_derivation(
    value: object,
    *,
    generated_path: str,
    generated_sha256: object,
    label: str,
    manifest_path: str | None = None,
    manifest_sha256: object = None,
) -> None:
    if not isinstance(value, dict):
        fail(f"{label} lacks rate_derivation")
    maximum_error = value.get(
        "maximum_absolute_stationary_reconstruction_error"
    )
    observed_error = value.get("maximum_absolute_observed_rate_error")
    target_error = value.get("maximum_absolute_stationary_target_error")
    reported_error = value.get(
        "maximum_absolute_reported_reconstruction_error"
    )
    manifest_duration = value.get("manifest_duration_seconds")
    if (
            value.get("schema_version") != 1
            or value.get("status") != "passed"
            or value.get("event_types_checked") != 6
            or isinstance(manifest_duration, bool)
            or not isinstance(manifest_duration, int)
            or manifest_duration <= 0
            or value.get("relative_tolerance") != 1.0e-12
            or value.get("absolute_tolerance") != 1.0e-12
            or value.get(
                "stationary_reconstruction_equals_target_per_type"
            ) is not True
            or value.get(
                "observed_rates_equal_manifest_counts_per_duration"
            ) is not True
            or value.get(
                "stationary_targets_equal_declared_transforms_per_type"
            ) is not True
            or value.get(
                "reported_reconstruction_equals_configured_rate_equation_per_type"
            ) is not True
            or value.get("transform_settings") != expected_hawkes
            or not isinstance(maximum_error, (int, float))
            or not math.isfinite(float(maximum_error))
            or float(maximum_error) < 0.0
            or not isinstance(observed_error, (int, float))
            or not math.isfinite(float(observed_error))
            or not 0.0 <= float(observed_error) <= 1.0e-12
            or not isinstance(target_error, (int, float))
            or not math.isfinite(float(target_error))
            or not 0.0 <= float(target_error) <= 1.0e-12
            or not isinstance(reported_error, (int, float))
            or not math.isfinite(float(reported_error))
            or float(reported_error) < 0.0):
        fail(f"{label} has an incomplete stationary-rate derivation audit")
    manifest = value.get("manifest")
    generated = value.get("generated_hawkes_rates")
    if not isinstance(manifest, dict) or not isinstance(generated, dict):
        fail(f"{label} does not bind its manifest and generated rate file")
    nested_manifest_path = valid_path(
        manifest.get("path"), f"{label} manifest",
    )
    if manifest_path is not None and nested_manifest_path != manifest_path:
        fail(f"{label} rate_derivation names a different source manifest")
    if manifest_sha256 is not None and manifest.get("sha256") != manifest_sha256:
        fail(f"{label} rate_derivation has a conflicting manifest hash")
    verify_sha256(
        nested_manifest_path, manifest.get("sha256"), f"{label} manifest",
    )
    nested_generated_path = valid_path(
        generated.get("path"), f"{label} generated Hawkes rates",
    )
    if nested_generated_path != generated_path:
        fail(f"{label} rate_derivation names a different generated rate file")
    if generated.get("sha256") != generated_sha256:
        fail(f"{label} rate_derivation has a conflicting generated-file hash")
    verify_sha256(
        nested_generated_path,
        generated.get("sha256"),
        f"{label} rate_derivation generated Hawkes rates",
    )

training = payload.get("training_days")
if not isinstance(training, list) or len(training) < 2:
    fail("training_days must be a list containing at least two sessions")
records = []
for entry in training:
    if not isinstance(entry, dict):
        fail("training_days contains a non-object entry")
    day = valid_date(entry.get("date"), "training day date")
    config = valid_path(entry.get("common_config"), f"training config for {day}")
    verify_sha256(
        config, entry.get("common_config_sha256"),
        f"training common_config for {day}",
    )
    targets = valid_path(entry.get("target_root"), f"training target root for {day}", directory=True)
    records.append((day, config, targets))
records.sort(key=lambda record: record[0])
if len({record[0] for record in records}) != len(records):
    fail("training_days contains duplicate dates")
actual_training = [record[0] for record in records]
if expected_training and actual_training != expected_training:
    fail(
        "training dates are " + ",".join(actual_training) +
        "; expected " + ",".join(expected_training)
    )

heldout_date = valid_date(payload.get("heldout_date"), "heldout_date")
if actual_training[-1] >= heldout_date:
    fail("every training date must be earlier than heldout_date")
if expected_heldout and heldout_date != expected_heldout:
    fail(f"heldout_date is {heldout_date}; expected {expected_heldout}")
heldout = payload.get("heldout")
if not isinstance(heldout, dict):
    fail("heldout is not an object")
heldout_config = valid_path(heldout.get("common_config"), "heldout common_config")
verify_sha256(
    heldout_config, heldout.get("common_config_sha256"), "heldout common_config",
)
heldout_targets = valid_path(heldout.get("target_root"), "heldout target_root", directory=True)
heldout_compatibility = heldout.get("quote_improvement_compatibility")
heldout_opening_fields = [
    "fundamental_price_ticks",
    "initial_best_bid_ticks",
    "initial_best_ask_ticks",
    "initial_best_bid_depth",
    "initial_best_ask_depth",
]
if (heldout.get("heldout_role")
            != "opening_state_and_validation_targets_only"
        or heldout.get("opening_fields_copied_from_heldout")
            != heldout_opening_fields
        or heldout.get("background_inputs_inherited_from_pooled") is not True
        or not isinstance(heldout_compatibility, dict)
        or heldout_compatibility.get("status")
            != "frozen_from_pooled_training"
        or heldout_compatibility.get("symbol_count") != eligible_count
        or heldout_compatibility.get("heldout_mark_inputs_instantiated")
            is not False
        or heldout_compatibility.get("runtime_probability_source")
            != "pooled_training_universe.csv"):
    fail(
        "heldout provenance does not certify inheritance of the checked "
        "pooled runtime backgrounds"
    )
pooled = payload.get("pooled_configuration")
if not isinstance(pooled, dict):
    fail("pooled_configuration is not an object")
pooled_config = valid_path(pooled.get("path"), "pooled configuration")
verify_sha256(pooled_config, pooled.get("sha256"), "pooled configuration")
pooled_targets = runtime_targets(pooled_config, "pooled configuration")
pooled_rate_paths = runtime_rate_paths(pooled_config, "pooled configuration")
training_rate_paths = {
    day: runtime_rate_paths(config, f"training config for {day}")
    for day, config, _ in records
}
for day, config, _ in records:
    if runtime_targets(config, f"training config for {day}") != pooled_targets:
        fail(
            f"training config for {day} does not freeze the pooled spread/depth targets"
        )
if runtime_targets(heldout_config, "heldout opening config") != pooled_targets:
    fail(
        "heldout opening config does not freeze the pooled spread/depth targets"
    )
if runtime_rate_paths(heldout_config, "heldout opening config") != pooled_rate_paths:
    fail("heldout opening config does not inherit the pooled Hawkes-rate files")

symbol_records = payload.get("symbols")
if not isinstance(symbol_records, list) or len(symbol_records) != eligible_count:
    fail("pooling provenance lacks one direct-rate record per eligible symbol")
seen_symbols: set[str] = set()
for record in symbol_records:
    if not isinstance(record, dict):
        fail("symbols contains a non-object record")
    symbol = str(record.get("symbol", "")).strip().upper()
    if not symbol or symbol in seen_symbols or symbol not in pooled_rate_paths:
        fail(f"symbols contains an invalid or duplicate symbol {symbol!r}")
    seen_symbols.add(symbol)

    pooled_manifest = valid_path(
        record.get("pooled_manifest"),
        f"pooled manifest for {symbol}",
    )
    pooled_rate = valid_path(
        record.get("pooled_hawkes_rates"),
        f"pooled Hawkes rates for {symbol}",
    )
    if pooled_rate != pooled_rate_paths[symbol]:
        fail(f"pooled config names a different Hawkes-rate file for {symbol}")
    verify_sha256(
        pooled_rate, record.get("pooled_hawkes_rates_sha256"),
        f"pooled Hawkes rates for {symbol}",
    )
    verify_rate_derivation(
        record.get("rate_derivation"),
        generated_path=pooled_rate,
        generated_sha256=record.get("pooled_hawkes_rates_sha256"),
        label=f"pooled {symbol}",
        manifest_path=pooled_manifest,
    )

    sources = record.get("sources")
    if not isinstance(sources, list) or len(sources) != len(actual_training):
        fail(f"daily direct-rate records are incomplete for {symbol}")
    sources_by_date = {
        str(source.get("trading_date")): source
        for source in sources if isinstance(source, dict)
    }
    if set(sources_by_date) != set(actual_training):
        fail(f"daily direct-rate dates are malformed for {symbol}")
    for day in actual_training:
        source = sources_by_date[day]
        source_manifest = valid_path(
            source.get("manifest"),
            f"source manifest for {symbol} {day}",
        )
        verify_sha256(
            source_manifest, source.get("manifest_sha256"),
            f"source manifest for {symbol} {day}",
        )
        generated_rate = valid_path(
            source.get("generated_hawkes_rates"),
            f"generated Hawkes rates for {symbol} {day}",
        )
        source_rate = valid_path(
            source.get("source_hawkes_rates"),
            f"source Hawkes rates for {symbol} {day}",
        )
        if generated_rate != training_rate_paths[day].get(symbol):
            fail(
                f"training config for {day} does not use its generated direct "
                f"Hawkes rates for {symbol}"
            )
        verify_sha256(
            generated_rate, source.get("generated_hawkes_rates_sha256"),
            f"generated Hawkes rates for {symbol} {day}",
        )
        verify_sha256(
            source_rate, source.get("source_hawkes_rates_sha256"),
            f"source Hawkes rates for {symbol} {day}",
        )
        verify_rate_derivation(
            source.get("rate_derivation"),
            generated_path=generated_rate,
            generated_sha256=source.get("generated_hawkes_rates_sha256"),
            label=f"daily {symbol} {day}",
            manifest_path=source_manifest,
            manifest_sha256=source.get("manifest_sha256"),
        )
if seen_symbols != set(pooled_rate_paths):
    fail("pooled configuration and symbol direct-rate records disagree")

print("heldout_date\t" + heldout_date)
print("heldout_config\t" + heldout_config)
print("heldout_targets\t" + heldout_targets)
print("pooled_config\t" + pooled_config)
for day, config, targets in records:
    print("training\t" + day + "\t" + config + "\t" + targets)
PY
)" || fail "could not parse MULTIDAY_POOLING_PROVENANCE=${manifest}"

declare -ga MULTIDAY_TRAINING_DATES=()
declare -ga MULTIDAY_TRAINING_CONFIGS=()
declare -ga MULTIDAY_TRAINING_TARGET_ROOTS=()
MULTIDAY_HELDOUT_DATE=""
MULTIDAY_HELDOUT_CONFIG=""
MULTIDAY_HELDOUT_TARGET_ROOT=""
MULTIDAY_POOLED_CONFIG=""
local kind first second third
while IFS=$'\t' read -r kind first second third; do
    case "${kind}" in
        heldout_date) MULTIDAY_HELDOUT_DATE="${first}" ;;
        heldout_config) MULTIDAY_HELDOUT_CONFIG="${first}" ;;
        heldout_targets) MULTIDAY_HELDOUT_TARGET_ROOT="${first}" ;;
        pooled_config) MULTIDAY_POOLED_CONFIG="${first}" ;;
        training)
            MULTIDAY_TRAINING_DATES+=("${first}")
            MULTIDAY_TRAINING_CONFIGS+=("${second}")
            MULTIDAY_TRAINING_TARGET_ROOTS+=("${third}")
            ;;
        *) fail "unexpected provenance row type '${kind}'" ;;
    esac
done <<< "${rows}"
if (( ${#MULTIDAY_TRAINING_DATES[@]} < 2 )) \
        || [[ -z "${MULTIDAY_HELDOUT_DATE}" ]] \
        || [[ -z "${MULTIDAY_HELDOUT_CONFIG}" ]] \
        || [[ -z "${MULTIDAY_HELDOUT_TARGET_ROOT}" ]] \
        || [[ -z "${MULTIDAY_POOLED_CONFIG}" ]]; then
    fail "MULTIDAY_POOLING_PROVENANCE yielded an incomplete calibration manifest"
fi
}

split_values() {
    local text="$1"
    text="${text//,/ }"
    read -r -a PARSED_VALUES <<< "${text}"
    (( ${#PARSED_VALUES[@]} > 0 )) || fail "list must not be empty"
}

positive_integer CLUSTERS "${CLUSTERS}"
positive_integer VALIDATION_PER_CLUSTER "${VALIDATION_PER_CLUSTER}"
positive_integer STAGE1_DURATION "${STAGE1_DURATION}"
positive_integer STAGE2_DURATION "${STAGE2_DURATION}"
positive_integer SESSION_DURATION "${SESSION_DURATION}"
positive_integer STAGE1_TOP_CANDIDATES "${STAGE1_TOP_CANDIDATES}"
[[ "${STAGE1_REFINEMENT_CANDIDATES}" =~ ^[0-9]+$ ]] \
    || fail "STAGE1_REFINEMENT_CANDIDATES must be a non-negative integer"
positive_integer STAGE2_TOP_CANDIDATES "${STAGE2_TOP_CANDIDATES}"

if ! type module >/dev/null 2>&1 && [[ -r /etc/profile.d/lmod.sh ]]; then
    source /etc/profile.d/lmod.sh
fi
type module >/dev/null 2>&1 || fail "module command is unavailable"
module purge
# Intentional word splitting: SEAGULL_MODULES is a whitespace-separated list.
module load ${SEAGULL_MODULES}
for executable in cmake ninja mpicxx mpirun python3; do
    command -v "${executable}" >/dev/null 2>&1 \
        || fail "${executable} is unavailable after loading SEAGULL_MODULES"
done

MPI_LIB_DIR="$(mpicxx --showme:libdirs | awk '{print $1}')"
[[ -n "${MPI_LIB_DIR}" && -d "${MPI_LIB_DIR}" ]] \
    || fail "could not determine OpenMPI library directory"
export LD_LIBRARY_PATH="${MPI_LIB_DIR}${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"
export OMP_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 MKL_NUM_THREADS=1
ulimit -s unlimited

DETERMINISTIC_BUILD_CONTRACT="${PROJECT_DIR}/scripts/seagull_deterministic_build.sh"
[[ -r "${DETERMINISTIC_BUILD_CONTRACT}" ]] \
    || fail "missing deterministic build contract: ${DETERMINISTIC_BUILD_CONTRACT}"
# shellcheck source=scripts/seagull_deterministic_build.sh
source "${DETERMINISTIC_BUILD_CONTRACT}"

cd "${PROJECT_DIR}"
MULTIDAY_POOLING_PROVENANCE="$(absolute_file "${MULTIDAY_POOLING_PROVENANCE}")"
POOLING_PRODUCER_PROJECT_ROOT="$(
    absolute_directory "${POOLING_PRODUCER_PROJECT_ROOT}"
)"
python3 - "${PROJECT_DIR}" "${MULTIDAY_POOLING_PROVENANCE}" \
    "${POOLING_PRODUCER_PROJECT_ROOT}" <<'PY'
import json
import pathlib
import sys

project = pathlib.Path(sys.argv[1]).resolve()
manifest = pathlib.Path(sys.argv[2]).resolve()
producer = pathlib.Path(sys.argv[3]).resolve()
sys.path.insert(0, str(project / "scripts"))
import calibrate_cluster_value_agents as calibration

payload = json.loads(manifest.read_text(encoding="utf-8"))
verification = calibration.validate_pooling_producer_workflow_source(
    payload,
    producer_project_root=producer,
    consumer_project_root=project,
)
print(json.dumps(
    {"pooling_producer_source_verification": verification},
    sort_keys=True,
))
PY
load_multiday_pooling_provenance \
    "${MULTIDAY_POOLING_PROVENANCE}" \
    "${MULTIDAY_EXPECTED_TRAINING_DATES}" \
    "${MULTIDAY_EXPECTED_HELDOUT_DATE}"
# These names are used by common reporting and the development-validation run.
# Candidate evaluation itself receives every entry in the arrays below.
HELDOUT_TARGET_ROOT="${MULTIDAY_HELDOUT_TARGET_ROOT}"
HELDOUT_DATE="${MULTIDAY_HELDOUT_DATE}"

split_values "${STAGE1_SEEDS}"; STAGE1_SEED_VALUES=("${PARSED_VALUES[@]}")
split_values "${STAGE2_SEEDS}"; STAGE2_SEED_VALUES=("${PARSED_VALUES[@]}")
split_values "${STAGE3_SEEDS}"; STAGE3_SEED_VALUES=("${PARSED_VALUES[@]}")
split_values "${THRESHOLDS}"; THRESHOLD_VALUES=("${PARSED_VALUES[@]}")
split_values "${DEPTH_PARTICIPATIONS}"; DEPTH_PARTICIPATION_VALUES=("${PARSED_VALUES[@]}")
split_values "${HAWKES_ACTIVITY_SCALES}"; HAWKES_ACTIVITY_SCALE_VALUES=("${PARSED_VALUES[@]}")
split_values "${LOCAL_MM_INTERVALS_MS}"; LOCAL_MM_INTERVAL_VALUES=("${PARSED_VALUES[@]}")
split_values "${LOCAL_MM_QUANTITY_MULTIPLIERS}"; LOCAL_MM_QUANTITY_MULTIPLIER_VALUES=("${PARSED_VALUES[@]}")
split_values "${LOCAL_MM_IMPROVEMENT_PROBABILITIES}"; LOCAL_MM_IMPROVEMENT_PROBABILITY_VALUES=("${PARSED_VALUES[@]}")
split_values "${SHARED_QUOTE_MULTIPLIERS}"; SHARED_QUOTE_MULTIPLIER_VALUES=("${PARSED_VALUES[@]}")

mkdir -p "${RESULT_DIR}" "${PROJECT_DIR}/slurm"
echo "== CLUSTER VALUE-AGENT CALIBRATION =="
date --iso-8601=seconds
echo "job_id=${SLURM_JOB_ID} node_list=${SLURM_JOB_NODELIST}"
echo "training_dates=${MULTIDAY_TRAINING_DATES[*]} heldout=${HELDOUT_DATE} clusters=${CLUSTERS}"
echo "pooling_provenance=${MULTIDAY_POOLING_PROVENANCE}"
echo "pooling_producer_project_root=${POOLING_PRODUCER_PROJECT_ROOT}"
echo "pooled_training_config=${MULTIDAY_POOLED_CONFIG}"
module list 2>&1 || true

lob_deterministic_configure_and_build \
    "${PROJECT_DIR}" "${BUILD_DIR}" "${MPI_LIB_DIR}" "${BUILD_JOBS}"
# Run the complete local/single-process contract, including book accounting,
# empirical marks, model semantics, configuration, hashes and singleton MPI.
# Multi-rank tests are excluded here because Slurm/OpenMPI launch integration
# is cluster-specific and is exercised by the separately submitted scaling
# workflow; silently selecting only three smoke tests is not sufficient for a
# calibration binary.
ctest --test-dir "${BUILD_DIR}" \
    --output-on-failure \
    --no-tests=error \
    -E '_mpi_[2-9][0-9]*$'

CALIBRATION_BUILD_PROVENANCE="${RESULT_DIR}/calibration_build_provenance.json"
python3 - "${PROJECT_DIR}" "${BUILD_DIR}/fragmented_mpi_lob" \
    "${CALIBRATION_BUILD_PROVENANCE}" \
    "${DETERMINISTIC_BUILD_CONTRACT}" \
    "${LOB_DETERMINISTIC_BUILD_CONTRACT_VERSION}" \
    "${LOB_DETERMINISTIC_SOURCE_DATE_EPOCH}" \
    "${MPI_LIB_DIR}" "$(command -v mpicxx)" "$(command -v ninja)" <<'PY'
import hashlib
import json
import pathlib
import subprocess
import sys

project = pathlib.Path(sys.argv[1]).resolve()
binary = pathlib.Path(sys.argv[2]).resolve()
output = pathlib.Path(sys.argv[3]).resolve()
contract = pathlib.Path(sys.argv[4]).resolve()
contract_version = sys.argv[5]
source_date_epoch = sys.argv[6]
mpi_lib_dir = pathlib.Path(sys.argv[7]).resolve()
compiler_path = pathlib.Path(sys.argv[8]).resolve()
ninja_path = pathlib.Path(sys.argv[9]).resolve()
sys.path.insert(0, str(project / "scripts"))
import calibrate_cluster_value_agents as calibration

if not binary.is_file():
    raise SystemExit(f"ERROR: calibration executable is missing: {binary}")
if not contract.is_file():
    raise SystemExit(f"ERROR: deterministic build contract is missing: {contract}")
payload = {
    "schema_version": 1,
    "artifact_role": "calibration_build_provenance",
    "cmake_build_type": "Release",
    "binary": str(binary),
    "binary_sha256": hashlib.sha256(binary.read_bytes()).hexdigest(),
    "simulator_source_semantics_sha256": (
        calibration.simulator_source_semantics_sha256(project)
    ),
    "workflow_source_semantics_sha256": (
        calibration.workflow_source_semantics_sha256(project)
    ),
    "compiler": subprocess.check_output(
        ["mpicxx", "--version"], text=True
    ).splitlines()[0],
    "mpi": subprocess.check_output(
        ["mpirun", "--version"], text=True
    ).splitlines()[0],
    "deterministic_build_contract": {
        "version": contract_version,
        "path": str(contract),
        "sha256": hashlib.sha256(contract.read_bytes()).hexdigest(),
        "compiler_path": str(compiler_path),
        "ninja_path": str(ninja_path),
        "mpi_lib_dir": str(mpi_lib_dir),
        "source_date_epoch": source_date_epoch,
        "cmake_build_type": "Release",
        "lob_require_mpi": True,
        "lob_build_tests": True,
        "interprocedural_optimization": False,
    },
}
output.write_text(
    json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8"
)
PY

# The pooling job has already intersected all six empirical universes,
# canonicalised book IDs, injected the pooled feedback targets and recorded
# the exact paths/hashes. Re-intersecting here would define a second model.
TRAINING_COMMON_CONFIG="${MULTIDAY_POOLED_CONFIG}"
HELDOUT_COMMON_CONFIG="${MULTIDAY_HELDOUT_CONFIG}"

CLUSTER_DIR="${RESULT_DIR}/liquidity_clusters"
python3 "${PROJECT_DIR}/scripts/cluster_empirical_universe.py" \
    --universe-config "${TRAINING_COMMON_CONFIG}" \
    --output-dir "${CLUSTER_DIR}" \
    --clusters "${CLUSTERS}" \
    --validation-per-cluster "${VALIDATION_PER_CLUSTER}" \
    --minimum-cluster-size "${MINIMUM_CLUSTER_SIZE}" \
    --seed "${CLUSTER_SEED}"

CALIBRATION_TRAINING_ARGS=(
    --pooled-training-universe-config "${MULTIDAY_POOLED_CONFIG}"
)
for (( index = 0; index < ${#MULTIDAY_TRAINING_DATES[@]}; ++index )); do
    CALIBRATION_TRAINING_ARGS+=(
        --training-day "${MULTIDAY_TRAINING_DATES[index]}"
        "${MULTIDAY_TRAINING_CONFIGS[index]}"
        "${MULTIDAY_TRAINING_TARGET_ROOTS[index]}"
    )
done

CALIBRATION_ARGS=(
    python3 "${PROJECT_DIR}/scripts/calibrate_cluster_value_agents.py"
    --binary "${BUILD_DIR}/fragmented_mpi_lob"
    --build-provenance "${CALIBRATION_BUILD_PROVENANCE}"
    "${CALIBRATION_TRAINING_ARGS[@]}"
    --heldout-opening-source-config "${HELDOUT_COMMON_CONFIG}"
    --cluster-assignments "${CLUSTER_DIR}/cluster_assignments.csv"
    --validation-sample "${CLUSTER_DIR}/validation_sample.csv"
    --cluster-manifest "${CLUSTER_DIR}/cluster_manifest.json"
    --heldout-date "${HELDOUT_DATE}"
    --heldout-target-root "${HELDOUT_TARGET_ROOT}"
    --output-dir "${RESULT_DIR}/calibration"
    --launcher "mpirun --bind-to core --map-by slot -np 1"
    --stage1-duration "${STAGE1_DURATION}" --stage2-duration "${STAGE2_DURATION}"
    --stage3-duration "${SESSION_DURATION}" --session-duration "${SESSION_DURATION}"
    --stage1-top-candidates "${STAGE1_TOP_CANDIDATES}"
    --stage1-refinement-candidates "${STAGE1_REFINEMENT_CANDIDATES}"
    --stage2-top-candidates "${STAGE2_TOP_CANDIDATES}"
    --stage1-seeds "${STAGE1_SEED_VALUES[@]}"
    --stage2-seeds "${STAGE2_SEED_VALUES[@]}"
    --stage3-seeds "${STAGE3_SEED_VALUES[@]}"
    --thresholds "${THRESHOLD_VALUES[@]}"
    --depth-participations "${DEPTH_PARTICIPATION_VALUES[@]}"
    --hawkes-activity-scales "${HAWKES_ACTIVITY_SCALE_VALUES[@]}"
    --local-mm-intervals-ms "${LOCAL_MM_INTERVAL_VALUES[@]}"
    --local-mm-quantity-multipliers "${LOCAL_MM_QUANTITY_MULTIPLIER_VALUES[@]}"
    --local-mm-improvement-probabilities "${LOCAL_MM_IMPROVEMENT_PROBABILITY_VALUES[@]}"
    --shared-quote-multipliers "${SHARED_QUOTE_MULTIPLIER_VALUES[@]}"
    --shared-treatment-multiplier "${SHARED_TREATMENT_MULTIPLIER}"
    --timeout-seconds "${TIMEOUT_SECONDS}"
    --marketwide-validation
    --require-certification-profile
    --pooling-provenance "${MULTIDAY_POOLING_PROVENANCE}"
    --pooling-producer-project-root "${POOLING_PRODUCER_PROJECT_ROOT}"
)

# `tee` opens its destination before the calibration process starts.  Writing
# directly to calibration_result.json would therefore leave a zero-byte or
# partial file when Python fails, which could be mistaken for a terminal
# result.  Capture stdout in a hidden same-directory temporary file, validate
# that it is one JSON object, and rename it atomically only after the complete
# pipeline succeeds.  With `set -o pipefail`, any simulator/calibrator failure
# still terminates the job while the Python-written checkpoints remain in
# ${RESULT_DIR}/calibration for diagnosis.
CALIBRATION_RESULT_PATH="${RESULT_DIR}/calibration_result.json"
[[ ! -e "${CALIBRATION_RESULT_PATH}" ]] \
    || fail "refusing to overwrite existing ${CALIBRATION_RESULT_PATH}"
CALIBRATION_RESULT_TMP="$(
    mktemp "${RESULT_DIR}/.calibration_result.${SLURM_JOB_ID}.XXXXXX"
)"
CALIBRATION_CERTIFICATION_PATH="${RESULT_DIR}/calibration/independent_global_calibration_certification.json"
CALIBRATION_CERTIFICATION_TMP=""
cleanup_calibration_result_tmp() {
    if [[ -n "${CALIBRATION_RESULT_TMP:-}" ]]; then
        rm -f -- "${CALIBRATION_RESULT_TMP}"
    fi
    if [[ -n "${CALIBRATION_CERTIFICATION_TMP:-}" ]]; then
        rm -f -- "${CALIBRATION_CERTIFICATION_TMP}"
    fi
}
trap cleanup_calibration_result_tmp EXIT

"${CALIBRATION_ARGS[@]}" | tee "${CALIBRATION_RESULT_TMP}"
python3 - "${CALIBRATION_RESULT_TMP}" <<'PY'
import json
import pathlib
import sys

path = pathlib.Path(sys.argv[1])
try:
    payload = json.loads(path.read_text(encoding="utf-8"))
except (OSError, json.JSONDecodeError) as error:
    raise SystemExit(f"ERROR: calibration stdout is not valid JSON: {error}")
if not isinstance(payload, dict):
    raise SystemExit("ERROR: calibration stdout JSON is not an object")
PY

# A handoff is necessary but not sufficient. Independently reopen all 35
# full-session runs and their logs, recompute every frozen gate, and publish a
# PASS record atomically. The case-study launcher requires and reruns this
# verifier, so a stale handoff or a hand-written `passed: true` cannot grant
# downstream authority.
if [[ ! -f "${RESULT_DIR}/calibration/calibration_handoff.json" ]]; then
    echo "calibration_handoff=NOT_CERTIFIED"
    echo "preliminary_result=${RESULT_DIR}/calibration/preliminary_calibration_result.json"
    fail "development validation did not produce calibration_handoff.json; outputs were preserved for diagnosis and the case study remains blocked"
fi
[[ ! -e "${CALIBRATION_CERTIFICATION_PATH}" ]] \
    || fail "refusing to overwrite existing ${CALIBRATION_CERTIFICATION_PATH}"
CALIBRATION_CERTIFICATION_TMP="$(
    mktemp "${RESULT_DIR}/calibration/.independent_global_certification.${SLURM_JOB_ID}.XXXXXX"
)"
python3 "${PROJECT_DIR}/scripts/verify_global_calibration_certification.py" \
    --project-root "${PROJECT_DIR}" \
    --calibration-root "${RESULT_DIR}/calibration" \
    --binary "${BUILD_DIR}/fragmented_mpi_lob" \
    --build-provenance "${CALIBRATION_BUILD_PROVENANCE}" \
    > "${CALIBRATION_CERTIFICATION_TMP}"
python3 - "${CALIBRATION_CERTIFICATION_TMP}" <<'PY'
import json
import pathlib
import sys

path = pathlib.Path(sys.argv[1])
try:
    payload = json.loads(path.read_text(encoding="utf-8"))
except (OSError, json.JSONDecodeError) as error:
    raise SystemExit(f"ERROR: independent certification output is invalid: {error}")
if not isinstance(payload, dict):
    raise SystemExit("ERROR: independent certification output is not a JSON object")
if payload.get("artifact_role") != "independent_global_calibration_certification":
    raise SystemExit("ERROR: independent certification output has the wrong role")
if payload.get("status") != "PASS":
    raise SystemExit("ERROR: independent certification did not return PASS")
PY
mv -- "${CALIBRATION_CERTIFICATION_TMP}" "${CALIBRATION_CERTIFICATION_PATH}"
CALIBRATION_CERTIFICATION_TMP=""

# Publish the captured calibrator stdout only after independent certification
# succeeds. A failed verifier therefore leaves diagnostics but no wrapper-level
# successful result.
mv -- "${CALIBRATION_RESULT_TMP}" "${CALIBRATION_RESULT_PATH}"
CALIBRATION_RESULT_TMP=""

echo "result_dir=${RESULT_DIR}"
echo "training_direct_input_config=${TRAINING_COMMON_CONFIG}"
echo "heldout_opening_source_config=${HELDOUT_COMMON_CONFIG}"
echo "training_pooling_provenance=${MULTIDAY_POOLING_PROVENANCE}"
echo "pooling_producer_project_root=${POOLING_PRODUCER_PROJECT_ROOT}"
echo "policy_csv=${RESULT_DIR}/calibration/cluster_value_agent_policy.csv"
echo "calibration_handoff=${RESULT_DIR}/calibration/calibration_handoff.json"
echo "independent_certification=${CALIBRATION_CERTIFICATION_PATH}"
date --iso-8601=seconds
