#ifndef HAWKES_PROCESS_HPP
#define HAWKES_PROCESS_HPP
#include <optional>
#include <array>
#include <cstdint>
#include <random>
#include <string>
#include <vector>

// We use 6 event types in the Hawkes process.
constexpr int NUM_EVENT_TYPES = 6;

// These are the six order-flow event types generated by the Hawkes process.
enum class EventType {
    LimitBuy = 0,
    LimitSell = 1,
    MarketBuy = 2,
    MarketSell = 3,
    CancelBid = 4,
    CancelAsk = 5
};

// Convert an EventType to readable text.
// Useful for printing/debugging.
std::string event_type_to_string(EventType type);

// One generated Hawkes event.
// It only contains:
//   1. event time
//   2. event type
struct HawkesEvent {
    std::int64_t time_ns;
    EventType type;
};

class HawkesProcess {
public:
    // A 6-element vector:
    // mu[0], ..., mu[5]
    using Vector6 = std::array<double, NUM_EVENT_TYPES>;

    // A 6 x 6 matrix:
    // alpha[future_event_type][past_event_type]
    using Matrix6 = std::array<std::array<double, NUM_EVENT_TYPES>, NUM_EVENT_TYPES>;

private:
    Vector6 mu_;
    Matrix6 alpha_;
    double beta_;

    std::vector<HawkesEvent> history_;

    std::mt19937_64 rng_;
    std::uniform_real_distribution<double> uniform_;

public:
    HawkesProcess(
        const Vector6& mu,
        const Matrix6& alpha,
        double beta,
        std::uint64_t seed
    );

    Vector6 compute_intensity(double t) const;

    double total_intensity(const Vector6& lambda) const;

    EventType sample_event_type(const Vector6& lambda, double total_lambda);

    std::vector<HawkesEvent> simulate(std::int64_t start_time_ns,std::int64_t end_time_ns);

    const std::vector<HawkesEvent>& history() const;
    std::optional<HawkesEvent> simulate_next(
        std::int64_t current_time_ns,
        std::int64_t end_time_ns,
        const Vector6& state_multiplier
    );
};

#endif
