#!/usr/bin/env python3
# Project code developed for Peter Zhang's thesis with OpenAI assistance; see PROVENANCE.md.
"""Generate docs/CODE_STRUCTURE.md from the current repository layout."""

from __future__ import annotations

import argparse
from collections import defaultdict
from pathlib import Path

EXCLUDED_DIRS = {
    ".git",
    ".idea",
    ".vscode",
    "__pycache__",
    "calibration_results",
    "results",
    "validation",
}
EXCLUDED_SUFFIXES = {".o", ".a", ".so", ".out", ".err", ".swp", ".zip", ".gz"}

DESCRIPTIONS = {
    "agents": "Strategic-agent implementations and the rank-local wake-time scheduler.",
    "calibration": "Eight-parameter model, empirical targets, recorders, and legacy SMC-ABC code.",
    "common": "Shared data types, configuration, empirical distributions, and performance metrics.",
    "exchange": "Rank-0 Hawkes flow, authoritative order book, matching, and event ordering.",
    "mpi": "Event-driven transport, shared-memory snapshot, and legacy fixed-window transport.",
    "simulation": "Forward-model orchestration and runtime mode selection.",
    "tests": "Unit, local integration, and real-MPI tests when MPI is available.",
    "slurm": "Callan smoke, full-day, staged calibration, and legacy comparison jobs.",
    "scripts": "Design generation, result collection, replication, and TuRBO proposal utilities.",
    "data": "Empirical distributions extracted from Nasdaq ITCH messages.",
    "docs": "Architecture, calibration, migration, and generated structure documentation.",
    "root": "Build system, entry points, installation, validation, and repository metadata.",
    "other": "Other repository resources.",
}


def excluded(path: Path, root: Path) -> bool:
    rel = path.relative_to(root)
    if any(part in EXCLUDED_DIRS or part.startswith("build") for part in rel.parts):
        return True
    return path.is_file() and path.suffix in EXCLUDED_SUFFIXES


def category(path: Path, root: Path) -> str:
    parts = path.relative_to(root).parts
    if len(parts) == 1:
        return "root"
    top = parts[0]
    if top in {"tests", "slurm", "scripts", "data", "docs"}:
        return top
    if top in {"src", "include"} and len(parts) >= 2:
        second = parts[1]
        if second in {"agents", "calibration", "common", "exchange", "mpi", "simulation"}:
            return second
        return "root"
    if top == "calibration":
        return "calibration"
    return "other"


def build_tree(paths: list[Path]) -> list[str]:
    tree: dict[str, dict] = {}
    for path in paths:
        node = tree
        for part in path.parts:
            node = node.setdefault(part, {})

    lines: list[str] = []

    def walk(node: dict[str, dict], prefix: str = "") -> None:
        entries = sorted(node.items(), key=lambda item: (not bool(item[1]), item[0].lower()))
        for index, (name, children) in enumerate(entries):
            last = index == len(entries) - 1
            lines.append(f"{prefix}{'└── ' if last else '├── '}{name}")
            if children:
                walk(children, prefix + ("    " if last else "│   "))

    walk(tree)
    return lines


def render(root: Path) -> str:
    grouped: dict[str, list[Path]] = defaultdict(list)
    all_paths: list[Path] = []
    for path in sorted(root.rglob("*")):
        if not path.is_file() or excluded(path, root):
            continue
        rel = path.relative_to(root)
        grouped[category(path, root)].append(rel)
        all_paths.append(rel)

    output = [
        "# Code Structure",
        "",
        "> Generated by `scripts/generate_code_structure.py`. Do not edit manually.",
        "",
        "## Repository tree",
        "",
        "```text",
        f"{root.name}/",
    ]
    output.extend(f"    {line}" for line in build_tree(all_paths))
    output.extend(["```", "", "## Subsystems", ""])

    order = [
        "root", "exchange", "agents", "mpi", "simulation", "calibration",
        "common", "tests", "data", "scripts", "slurm", "docs", "other",
    ]
    for name in order:
        paths = grouped.get(name)
        if not paths:
            continue
        output.extend([
            f"### {name.replace('_', ' ').title()}",
            "",
            DESCRIPTIONS[name],
            "",
        ])
        output.extend(f"- `{path.as_posix()}`" for path in paths)
        output.append("")

    output.extend([
        "## Runtime ownership",
        "",
        "```text",
        "Rank 0  : Hawkes process, authoritative LOB, matching engine, event queue",
        "Rank 1  : market-maker agents and local wake queue",
        "Rank 2  : momentum agents and local wake queue",
        "Rank 3  : informed agents and local wake queue",
        "Rank 4  : institutional agents and local wake queue",
        "```",
        "",
    ])
    return "\n".join(output)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument("--output", type=Path, default=Path("docs/CODE_STRUCTURE.md"))
    args = parser.parse_args()

    root = args.root.resolve()
    if not (root / "CMakeLists.txt").is_file():
        raise SystemExit(f"ERROR: CMakeLists.txt was not found under {root}")
    output = args.output if args.output.is_absolute() else root / args.output
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render(root), encoding="utf-8")
    print(f"Generated {output}")


if __name__ == "__main__":
    main()
